apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dp
  labels:
    app: frontend-dp
    type: frontend
spec:
  template:
    metadata:
      name: frontend-dp
      labels:
        app: frontend-app
        type: frontend
    spec:
      containers:
        - name: frontend-container
          image: nginx:1.18
  selector:
    matchLabels:
      type: frontend
  replicas: 5
